apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: busybox-secret-provider
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    keyvaultName: {{ .Values.keyvaultName }}
    tenantId: {{ .Values.tenantId }}
    objects:  |
      array:
        - |
          objectName: mytestsecret
          objectType: secret
        - |
          objectName: anotherSecret
          objectType: secret
