apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
patches:
  - target:
      kind: HelmRelease
      name: busybox
    patch: |
      - op: add
        path: /spec/chart/spec/valuesFiles/-
        value:
          apps/busybox/dev/values.yaml
      - op: add
        path: /spec/chart/spec/valuesFiles/-
        value:
          apps/busybox/dev/values-ot.yaml
