apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
patches:
  - target:
      kind: HelmRelease
      name: siteconf
    patch: |
      - op: add
        path: /spec/chart/spec/valuesFiles/-
        value:
          apps/siteconf/sea/values.yaml
