apiVersion: v1
kind: Secret
metadata:
  name: acr-cred
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: #baseb4 encode {"auths":{"your_acr.azurecr.io":{"auth":"<base64 encoded username:password>"}}}
