apiVersion: v1
kind: Secret
metadata:
  name: secret-store-creds
  labels:
    secrets-store.csi.k8s.io/used: "true"
type: Opaque
data:
  clientid: "service principal client id | b64enc"
  clientsecret: "service principal client secret | b64enc"