apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: siteconf
spec:
  releaseName: siteconf
  interval: 12m
  install:
    disableWait: true
  upgrade:
    disableWait: true
  chart:
    spec:
      chart: charts/siteconf
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: siteconfcfg
      valuesFiles: []